-- Print full description of the table 'books' from the current database
-- Do NOT use DESCRIBE or EXPLAIN. Pass the database name to the mysql client.
-- Example:
--   mysql -u root -p alx_book_store < .\task_4.sql

SELECT
  C.COLUMN_NAME AS `Field`,
  C.COLUMN_TYPE AS `Type`,
  C.IS_NULLABLE AS `Null`,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE K
      JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
        ON K.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
        AND K.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA
      WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
        AND K.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND K.TABLE_NAME = C.TABLE_NAME
        AND K.COLUMN_NAME = C.COLUMN_NAME
    ) THEN 'PRI'
    WHEN EXISTS (
      SELECT 1
      FROM INFORMATION_SCHEMA.STATISTICS S
      WHERE S.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND S.TABLE_NAME = C.TABLE_NAME
        AND S.COLUMN_NAME = C.COLUMN_NAME
        AND S.NON_UNIQUE = 0
    ) THEN 'UNI'
    WHEN EXISTS (
      SELECT 1
      FROM INFORMATION_SCHEMA.STATISTICS S2
      WHERE S2.TABLE_SCHEMA = C.TABLE_SCHEMA
        AND S2.TABLE_NAME = C.TABLE_NAME
        AND S2.COLUMN_NAME = C.COLUMN_NAME
        AND S2.NON_UNIQUE = 1
    ) THEN 'MUL'
    ELSE ''
  END AS `Key`,
  C.COLUMN_DEFAULT AS `Default`,
  C.EXTRA AS `Extra`
FROM INFORMATION_SCHEMA.COLUMNS C
WHERE LOWER(C.TABLE_NAME) = 'books'
  AND C.TABLE_SCHEMA = DATABASE()
ORDER BY C.ORDINAL_POSITION;
